<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistCommandLinter' => 'lint/ArcanistCommandLinter.php',
    'OCLintLinter' => 'lint/OCLintLinter.php',
    'XcodebuildConfiguration' => 'lint/XcodebuildConfiguration.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistCommandLinter' => 'ArcanistLinter',
    'OCLintLinter' => 'ArcanistCommandLinter',
  ),
));
